myblog/blog/urls.py
from django.urls import path, register_converter
from blog import views, converters


register_converter(converters.FourDigitYearConverter, 'year4')

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('posts/', views.posts, name='posts'),
    path('post/<int:post_id>', views.post_num, name='post_id'),
    path('post/<slug:post_slug>', views.post_slug, name='post_slug'),
    path("archive/<year4:year>/", views.archive, name='archive'),
]

myblog/chat/urls.py
from django.urls import path
from chat import views

urlpatterns = [
    path('', views.all_chat),
    path('chat/<int:chat_id>', views.сhat),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('chat.urls')),
]


handler404 = page_not_found

myblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'ЧН', 'Черновик'
        PUBLISHED = 'ОП', 'Опубликован'

    title = models.CharField('Заголовок', max_length=150)
    slug = models.SlugField('slug',max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    text = models.TextField('Текст')
    publish = models.DateTimeField('Опубликован', default=timezone.now)
    created = models.DateTimeField('Создан', auto_now_add=True)
    update = models.DateTimeField('Обновлён', auto_now=True)
    status = models.CharField('', max_length=2,
                              choices=Status.choices, default=Status.DRAFT)

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title

myblog/chat/models.py
from django.db import models

# Create your models here.

myblog/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse
from .models import Post


def index(request):
    menu = ['Главная', 'Архив', 'Список постов', 'Войти']
    all_post = Post.objects.all()
    return render(request, 'blog/index.html', {'menu': menu, 'all_post': all_post})


def about(request):
    data = {'title': 'О сайте'}
    return render(request,  'blog/about.html', data)


def posts(request,):
    all_post = Post.objects.all()
    return render(request, 'blog/posts.html', {"all_post" : all_post})


def post_num(request, post_id):
      post = get_object_or_404(Post, pk=post_id)
      return render(request, 'blog/one_post.html', {'post': post})


def post_slug(request, post_slug):
    return HttpResponse(f"<h1>Пост {post_slug}</h1>")


def archive(request, year):
    if year > 2024:
        uri = reverse('post_slug', args=('music', ))
        return HttpResponseRedirect(uri)
    return HttpResponse(f"<h1>Архив по году {year}</h1>")


def page_not_found(request, exception):
    return HttpResponseNotFound("<h1>Страница не найдена</h1>")

myblog/chat/views.py
from django.shortcuts import render
from django.http import HttpResponse


def all_chat(request):
    return HttpResponse("Список чатов")


def сhat(request):
    return HttpResponse("Чат с определённым пользователем")

myblog/blog/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <meta charset="UTF-8">
      <title>{% block title%} {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Myblog</a>
<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"-->
<!--            data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"-->
<!--    >-->
<!--    </button>-->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Главная страница</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Список постов</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#"></a>-->
<!--        </li>-->
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Войти</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<na>
<!--<div>-->
<!--    <a href="{% url 'blog:home'%}"> Главная страница </a>-->
<!--</div>-->
</na>
 <main class="container">
        {% block content %}
        {% endblock %}
 </main>
</body>
</html>

myblog/blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>{{ title }}</h1>
</body>
</html>

myblog/blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %} Главная страница {% endblock %}

{% block content %}
<body>
<h1>Главная страница</h1>
<ul>
    {%for post in all_post%}
    {%  if post.status == 'ОП' %}
    <li>
        <h2><a href='{% url "blog:post_id" post.id %}'>{{post.title}}</a></h2>
        <p>{{post.text}}</p>
        {% if not forloop.last %}
        <hr>
        {% endif %}
    </li>
    {% endif %}
    {% endfor %}
</ul>
</body>
{% endblock %}

myblog/blog/templates/blog/one_post.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
  </head>
  <body>
    <h1>{{post.title|capfirst}}</h1>
    <p>{{post.text}}</p>
  </body>
</html>

myblog/blog/templates/blog/post.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
  </head>
  <body>
    <h1>{{post.title|capfirst}}</h1>
    <p>{{post.text}}</p>
  </body>
</html>

myblog/blog/templates/blog/posts.html
{% extends 'base.html' %}

{% block title %} Список постов{% endblock %}

{% block content %}
{%for post in all_post%}
    {%  if post.status == 'ОП' %}
        <h2><a href='{% url "blog:post_id" post.id %}'>{{post.title}}</a></h2>
    {% endif %}
    {% endfor %}
{% endblock %}

myblog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
</head>
<body>
<h1>Главная страница</h1>
</body>
</html>